name: test

on:
    pull_request:
        branches:
            - '**'
        types: [opened, synchronize, reopened, unlabeled]
    push:
        branches:
            - '**'
        paths-ignore:
            - 'docs/**'
            - 'examples/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bun install
            - run: bun ci
