name: test

on:
    workflow_dispatch:
    pull_request:
        branches:
            - '**'
        types: [opened, synchronize, reopened, unlabeled]
    push:
        branches:
            - 'main'
        paths-ignore:
            - 'docs/**'
            - 'examples/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun ci
